export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const GET_ALL_ACTIVE_GAMES_SUCCESS = 'GET_ALL_ACTIVE_GAMES_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';